name: weather_app_nt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.3
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  dio: ^5.7.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  intl: ^0.20.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3



flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/font/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Black.otf
        - asset: assets/font/Inter-Bold.otf
        - asset: assets/font/Inter-ExtraBold.otf
        - asset: assets/font/Inter-ExtraLight-BETA.otf
        - asset: assets/font/Inter-Light-BETA.otf
        - asset: assets/font/Inter-Medium.otf
        - asset: assets/font/Inter-Regular.otf
        - asset: assets/font/Inter-SemiBold.otf
        - asset: assets/font/Inter-Thin-BETA.otf